/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'umesht' at '5/29/17 11:41 AM' with Gradle 2.14.1
 *
 * @author umesht, @date 5/29/17 11:41 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
    	System.out.println("Hello");
    }
}
